version: "2"

volumes:
  spaces-web-bundler-cache:
  spaces-collab-npm-cache:
  spaces-postgres-data:
  spaces-mongo-data:
  spaces-redis-data:
  spaces-elasticsearch-data:

services:
  web: &web
    build:
      context: ./vendor/web
      dockerfile: dockerfiles/development
    command: bundle exec rails s -b 0.0.0.0 -p 5510
    volumes:
      - ./vendor/web:/app
      - spaces-web-bundler-cache:/bundler-cache
    ports:
      - "5510:5510"
    env_file:
      - .env.web
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgresql://postgres@postgres/spaces_development
    links:
      - redis
      - postgres
      - mongo
      - elasticsearch
      - mailcatcher

  web-worker:
    <<: *web
    entrypoint: "bundle exec"
    command: "sidekiq -C config/sidekiq.yml"
    ports: []

  web-test:
    <<: *web
    entrypoint: "bundle exec"
    command: ""
    ports: []
    environment:
      RAILS_ENV: test
      DATABASE_URL: postgresql://postgres@postgres/spaces_test

  collab:
    build:
      context: ./vendor/collab
      dockerfile: dockerfiles/development
    command: npm start
    volumes:
      - ./vendor/collab:/app
      - spaces-collab-npm-cache:/node_modules
    ports:
      - "5520:5520"
    env_file:
      - .env.collab
    links:
      - redis
      - mongo

  postgres:
    image: postgres:9.5.2
    volumes:
      - spaces-postgres-data:/var/lib/postgresql/data
    ports:
      - "5600:5432"
    env_file:
      - .env.postgres

  mongo:
    image: mongo:3.2
    volumes:
      - spaces-mongo-data:/data/db
    ports:
      - "27500:27017"
    command: mongod --smallfiles --logpath=/dev/null

  redis:
    image: redis:3.2
    ports:
      - "6500:6379"
    volumes:
      - spaces-redis-data:/data

  elasticsearch:
    image: elasticsearch:5.3
    ports:
      - "9292:9200"
      - "9393:9300"
    volumes:
      - spaces-elasticsearch-data:/usr/share/elasticsearch/data
    env_file:
      - .env.elasticsearch

  mailcatcher:
    image: schickling/mailcatcher:latest
    ports:
      - 1080:1080
