version: "2"

volumes:
  web-bundler-cache:
  collab-npm-cache:
  postgres-data:
  mongo-data:
  redis-data:
  elasticsearch-data:
  apt-cache:

services:
  web: &web
    build:
      context: ./vendor/web
      dockerfile: Dockerfile.development
    command: bundle exec rails s -b 0.0.0.0
    volumes:
      - ./vendor/web:/app
      - web-bundler-cache:/bundler-cache
    ports:
      - "5510:3000"
    env_file:
      - .env.web
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgresql://postgres@postgres/furrow_development
    links:
      - redis
      - postgres
      - mongo

  web-test:
    <<: *web
    entrypoint: "bundle exec"
    command: ""
    ports: []
    environment:
      RAILS_ENV: test
      DATABASE_URL: postgresql://postgres@postgres/furrow_test

  collab:
    build:
      context: ./vendor/collab
      dockerfile: Dockerfile.development
    command: npm start
    volumes:
      - ./vendor/collab:/app
      - collab-npm-cache:/node_modules
    ports:
      - "5520:3000"
    env_file:
      - .env.collab
    links:
      - redis
      - mongo

  postgres:
    image: postgres:9.5.2
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5600:5432"
    env_file:
      - .env.postgres

  mongo:
    image: mongo:3.2
    volumes:
      - mongo-data:/data/db
    ports:
      - "27500:27017"
    command: mongod --smallfiles --logpath=/dev/null

  redis:
    image: redis:3.2
    ports:
      - "6500:6379"
    volumes:
      - redis-data:/data

  elasticsearch:
    image: elasticsearch:5
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"

  # https://github.com/sameersbn/docker-apt-cacher-ng
  apt-cacher:
    image: sameersbn/apt-cacher-ng:latest
    volumes:
      - apt-cache:/var/cache/apt-cacher-ng
    ports:
      - "8200:3142"
    restart: always
