# Services
version: "2"
volumes:
  api-bundler-cache:
  db-data:
  mongo-data:
  redis-data:
services:
  api: &api
    build:
      context: ./vendors/api
      dockerfile: Dockerfile.development
    command: bundle exec rails s -b 0.0.0.0
    volumes:
      - ./vendors/api:/app
      - api-bundler-cache:/bundler-cache
    ports:
      - "5510:3000"
    env_file:
      - '.env.api'
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgresql://postgres@postgres/furrow_development
    links:
      - redis
      - postgres
      - mongo

  api-test:
    <<: *api
    entrypoint: "bundle exec"
    command: "rails test"
    ports: []
    environment:
      RAILS_ENV: test
      DATABASE_URL: postgresql://postgres@postgres/furrow_test

  collab:
    build:
      context: ./vendors/collab
      dockerfile: Dockerfile.development
    command: npm start
    ports:
      - "5520:8080"
    env_file:
      - '.env.collab'
    links:
      - redis
      - mongo

  web:
    image: danlynn/ember-cli:2.5.1
    volumes:
      - ./vendors/web:/myapp
    command: server --watcher polling
    ports:
      - "5530:4200"
      - "35729:35729"
    env_file:
      - '.env.api'

  postgres:
    image: postgres:9.5.2
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5600:5432"
    env_file:
      - '.env.postgres'

  mongo:
    image: mongo:3.2
    volumes:
      - mongo-data:/data/db
    ports:
      - "27500:27017"
    command: mongod --smallfiles --logpath=/dev/null

  redis:
    image: redis:3.2
    ports:
      - "6500:6379"
    volumes:
      - redis-data:/data
