version: "2"
volumes:
  db-data:
  api-bundler-cache:
services:
  web:
    image: danlynn/ember-cli:2.5.1
    volumes:
      - ./vendors/web:/myapp
    command: server --watcher polling
    ports:
      - "5500:4200"
      - "35729:35729"
    env_file:
      - '.env.api'
  api:
    build:
      context: ./vendors/api
      dockerfile: Dockerfile.development
    command: bundle exec rails s
    volumes:
      - ./vendors/api:/app
      - api-bundler-cache:/bundler-cache
    ports:
      - "5510:3000"
    env_file:
      - '.env.api'
  postgres:
    image: postgres:9.5.2
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5000:5432"
    env_file:
      - '.env.postgres'
